env:
  - GENERATOR_DIR=$TRAVIS_BUILD_DIR/packages/generator-liferay-bundle GENERATOR_TEST_DIR=$GENERATOR_DIR/qa

matrix:
    include:
        os: 
          - linux
          - osx

install: 
  - npm run lerna

language: node_js

node_js:
  - "8"

addons:
    chrome: stable

git:
    depth: 1

jdk: oraclejdk8s

jobs:
    include: 
        
        # - stage: javascript format tests

        # - script: npm run ci

        - stage: generator liferay bundle test
        
          before_script:
                # - docker pull vcatechnology/linux-mint
                - sh echo $GENERATOR_TEST_DIR
                - echo $GENERATOR_TEST_DIR
                - sh cd $GENERATOR_DIR && 'npm install -g'
                - sh cd $GENERATOR_TEST_DIR && 'node generate-samples.js'

          script: echo $GENERATOR_TEST_DIR


#        - stage: integration tests
#
#          before_script:
#              - export DISPLAY=:99.0
#              - sh -e /etc/init.d/xvfb start
#              - sleep 3
#
#          script:
#              - ./gradlew createDocker
#
#              - while sleep 30s; do echo "Start Docker still in progress..."; done &
#              - ./gradlew startDocker
#              - kill %1
#
#              - ./gradlew testIntegration
#
#          after_script:
#              - gem install typhoeus
#              - ruby ./osb-faro-functional-test/src/testIntegration/resources/testray/testray_import.rb

services:
    - docker

sudo: required

# before_install:

# cache:
#     directories:
#         - $HOME/.gradle/caches/
#         - $HOME/.gradle/wrapper/
#     timeout: 600